name       : systemd
version    : '247.8'
release    : 96
source     :
    - https://github.com/systemd/systemd-stable/archive/refs/tags/v247.8.tar.gz : 77d8c26764d74b8ba197361f50700e5c9c6b5883a8118227f5e42173025b5baf
license    :
    - LGPL-2.1-or-later
    - GPL-2.0-or-later
component  :
    - system.base
    - devel : system.devel
summary    : System and Service Manager
description: |
    systemd is a system and service manager for Linux, compatible with SysV and LSB init scripts. systemd provides aggressive parallelization capabilities, uses socket and D-Bus activation for starting services, offers on-demand starting of daemons, keeps track of processes using Linux control groups, supports snapshotting and restoring of the system state, maintains mount and automount points and implements an elaborate transactional dependency-based service control logic. It can work as a drop-in replacement for sysvinit.
autodep    : false
emul32     : yes
libsplit   : no
optimize   :
    - size
    - lto
builddeps  :
    - pkgconfig(libcryptsetup)
    - pkgconfig(libkmod)
    - pkgconfig32(blkid)
    - pkgconfig32(dbus-1)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(libcap)
    - pkgconfig32(libcurl)
    - pkgconfig32(liblzma)
    - pkgconfig32(mount)
    - pkgconfig32(zlib)
    - libgcrypt-devel
    - attr-devel
    - acl-devel
    - attr-32bit-devel
    - acl-32bit-devel
    - bzip2-devel
    - bzip2-32bit-devel
    - docbook-xml
    - gperf
    - gnu-efi-devel
    - libgcrypt-32bit-devel
    - libgpg-error-32bit-devel
    - pam-32bit-devel
    - rsync
rundeps    :
    - kernel-glue
    - libgcrypt
    - devel :
        - libgcrypt-devel
    - 32bit :
        - libgcrypt-32bit
    - 32bit-devel :
        - libgcrypt-32bit-devel
patterns   :
    - devel :
        - /usr/share/man/man3
        - /usr/share/pkgconfig
setup      : |
    %apply_patches
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        depends_emul32=false
    else
        depends_emul32=true
    fi
    %meson_configure --prefix=/usr \
                     --bindir=/usr/bin \
                     --sbindir=/usr/sbin \
                     -Dacl=true \
                     -Dapparmor=false \
                     -Dblkid=true \
                     -Ddefault-hierarchy="unified" \
                     -Ddns-over-tls='gnutls' \
                     -Dgnu-efi=$depends_emul32 \
                     -Dgnutls=true \
                     -Dhomed=false \
                     -Dhostnamed=$depends_emul32 \
                     -Dkmod=$depends_emul32 \
                     -Dlibcryptsetup=$depends_emul32 \
                     -Dlibcurl=true \
                     -Dlink-udev-shared=false \
                     -Dlocaled=$depends_emul32 \
                     -Dman=$depends_emul32 \
                     -Dmachined=$depends_emul32 \
                     -Dnetworkd=false \
                     -Dntp-servers='0.solus.pool.ntp.org 1.solus.pool.ntp.org 2.solus.pool.ntp.org 3.solus.pool.ntp.org' \
                     -Doomd=true \
                     -Dopenssl=false \
                     -Dpamlibdir=/lib/security \
                     -Dp11kit=false \
                     -Dpam=true \
                     -Dpolkit=true \
                     -Dresolve=true \
                     -Drootlibdir=%libdir% \
                     -Drootprefix=/usr \
                     -Drpmmacrosdir=no \
                     -Dselinux=false \
                     -Dsplit-usr=true \
                     -Dsysvinit-path=/etc/init.d \
                     -Dtimesyncd=$depends_emul32 \
                     -Dusers-gid=100 \
                     -Duserdb=false
build      : |
    %meson_build
    # They do something weird during build step and it overrides our change.
    %patch -p1 < $pkgfiles/0001-Provide-a-default-max-retention-and-size-policy.patch
install    : |
    %meson_install

    # Solus is responsible for its own glibc + PAM configuration, *not* systemd..
    rm -vrf $installdir/usr/share/factory/*

    # Provide compatibility for Chrome, etc
    ln -sv libudev.so.1 $installdir/%libdir%/libudev.so.0

    # Only need to do the rest of the stuff on 64-bit build
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        exit 0
    fi

    # Install compat dirs
    install -D -d -m 00755 $installdir/{sbin,bin,lib/udev}

    # Compat for old tools
    ln -sv ../usr/bin/udevadm $installdir/sbin/udevadm
    ln -sv ../usr/lib/systemd/systemd-udevd $installdir/lib/udev/udevd

    # Make sure systemd + init can be found
    ln -sv ../usr/lib/systemd/systemd $installdir/bin/systemd
    ln -sv ../usr/lib/systemd/systemd $installdir/sbin/init

    # Ensure sbin links exist too
    for control in reboot shutdown poweroff halt ; do
        ln -sv ../usr/bin/systemctl $installdir/sbin/$control
    done

    # These are unsupported by Solus, we use clr-boot-manager
    rm -rvf $installdir/etc/kernel
    rm -v $installdir/usr/bin/kernel-install
    rm -v $installdir/usr/share/bash-completion/completions/kernel-install

    # Required basic support
    install -m 00644 $pkgfiles/solus-base-groups.sysusers $installdir/usr/lib/sysusers.d/solus-base-groups.conf

    # Make assuming scripts happy
    ln -sv ../usr/bin/systemctl $installdir/bin/.

    # add fixed pam config
    rm -rf $installdir/{etc,usr/lib}/pam.d
    install -Dm00644 $pkgfiles/systemd-user.pam $installdir/usr/share/defaults/etc/pam.d/systemd-user
